// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4lPQB53KHAcEH90JcpEYJzigSf9ZmeRU',
    appId: '1:555330937820:web:a56465e97f2a54b6c82519',
    messagingSenderId: '555330937820',
    projectId: 'smaer-gym-latest',
    authDomain: 'smaer-gym-latest.firebaseapp.com',
    storageBucket: 'smaer-gym-latest.appspot.com',
    measurementId: 'G-PQ2VH1M30F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXv_HRX7x6hrf_npXrzUTxbXd23RZnDE4',
    appId: '1:555330937820:android:7732ec38e6e3a213c82519',
    messagingSenderId: '555330937820',
    projectId: 'smaer-gym-latest',
    storageBucket: 'smaer-gym-latest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzu3GrHxEYtJ8-Y-Ay6kUrE3Nw1VAxn9A',
    appId: '1:555330937820:ios:3a216c059120ad16c82519',
    messagingSenderId: '555330937820',
    projectId: 'smaer-gym-latest',
    storageBucket: 'smaer-gym-latest.appspot.com',
    androidClientId: '555330937820-m79890qe9gprsae57oepfcmmeh2t888m.apps.googleusercontent.com',
    iosClientId: '555330937820-478nhlh1pa4f33ap500ba7jnf1r9vgu1.apps.googleusercontent.com',
    iosBundleId: 'com.samerygym.tech',
  );
}
